language: java
jdk:
- oraclejdk8
script:
- test/run.sh
notifications:
  slack:
    secure: dygx7a6CJf458EWT8LpehLyIyafsPXAn+77ELPykbIVQzoN/vYZHWWzuYu7agoG44xrLEasLENPcK+6VClERFhaKl9TPfNGS846KtenTe4XURMr1Yv+SiQqrZ9ccr3tEaWzVtLKlOU5hzCZozevwJJLap3Xpc9hXNgo+QVrr53k=
